google-github-actions/auth

- .github/workflows/test.yaml
- README.md
- action.yml
- dist/index.js
- src/client.ts
- src/main.ts
This PR adds support for ID Token generation.
I think there are some use cases where we want to use impersonated service account's ID token to access IAM-protected resources (e.g. accessing Cloud Run services, IAP-protected endpoints, etc) from GitHub Actions.
* Made `id_token_audience` as an optional parameter since not all users want to mint an ID token.
* Fixed `includeEmail` parameter for [generateIdToken](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/generateIdToken) method with always `true` since I guess most users assume that by default. Probably we can add `id_token_includ_email` boolean parameter if users want to control that.
> Support ID Token generation

- README.md
This fixes the examples where the GitHub Action won't run in private repositories when the `read` permission is not set.
> Add read permission to examples in the Readme

- README.md
Updated documentation with the following:
- remove the step of getting the `WORKLOAD_IDENTITY_PROVIDER_ID` as it's not being needed and used anywhere
- update `Usage` and `Examples` to make it compliant with GitHub Actions so that someone can copy-paste the example code, without getting complains from actions validity
> docs: remove unnecessary steps and update examples

- .github/workflows/test.yaml
`github.head_ref` is only available in PRs, so the build failed on main
> chore: Handle non-pull request runs

- README.md
A small fix.
I noticed this when using attribute conditions.
`username` is passed to `repository_owner`, not `reponame`.
An example of mapping can also be found in [this GitHub Action documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token).
> docs: fix token format example in readme

- .github/workflows/test.yaml
- README.md
- action.yml
- dist/main/index.js
- dist/post/index.js
- package.json
- src/main.ts
- src/post.ts
- src/utils.ts
- tests/utils.test.ts
Fixes https://github.com/google-github-actions/auth/issues/66
> Clean up exported credentials when the workflow finishes

- .github/workflows/tag.yaml
When new tags are pushed, this will automatically create/update a "pointer" tag to the major version as `vMAJOR`. This will allow us to write docs that pin to `@vMAJOR` instead of worrying about pinning to specific MAJOR.MINOR.PATCH.
> Add workflow to update tag pointer

- README.md
- dist/main/index.js
- src/main.ts
- src/utils.ts
- tests/utils.test.ts
There have been a number of GitHub issues recently due to users not adding actions/checkout before calling "auth", which makes the credentials unavailable to future steps. Worse, some people are putting checkout _after_ auth, which overwrites the generated credentials with a checkout of the repo.
This adds a feature that emits a warning with the workspace is empty.
> feat: emit a warning when the workspace is empty

- README.md
Hi, I've added minor fix into readme to use right form GAR registry name.
note: [this line](https://github.com/google-github-actions/auth/blob/main/README.md?plain=1#L325) uses right form.
> doc: fix registry name example for GAR

- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- docs/TROUBLESHOOTING.md
Update actions/checkout to v3.
[actions/checkout](https://github.com/actions/checkout) has been released https://github.com/actions/checkout/releases/tag/v3.0.0.
> Update actions/checkout to v3

- README.md
Fixes https://github.com/google-github-actions/auth/issues/142
> docs: add a note about node16 on self-hosted runners

- README.md
- docs/TROUBLESHOOTING.md
> Document how GitHub secrets work

- README.md
- src/main.ts
> fix: update doc versions

- README.md
> Document possible issues with org policies

- README.md
> Note that Firebase Admin Node.js SDK doesn't support WLIF

- README.md
I really struggleded several days with this and thankfully i found https://github.com/google-github-actions/auth/issues/77#issuecomment-990371420
big thanks to @sethvargo ❤
as @dobromyslov already said, this should be documented
so I went ahead and created added a paragrah for this use case
> Document admission for all repos of an owner

- docs/SECURITY_CONSIDERATIONS.md
Fix doc regarding using assertion on IDs rather than names. They refer to IDs as integers, where those are actually strings, so we need to quote them.
I lost too many hours on this to let anyone else experience the same issue :D
> Security considerations: ids are strings, not integers

- README.md
- action.yml
- src/client/client.ts
- src/client/iamcredentials.ts
- src/client/service_account_key_json.ts
- src/client/workload_identity_federation.ts
- src/main.ts
Fixes https://github.com/google-github-actions/auth/issues/412
> Add request_reason for plumbing though user-supplied audit information

- src/main.ts
Small change! This error message seems like it's missing a word, so based on the comment on line 202, I changed it 
from
> `⚠️ Failed to a project ID from the given inputs.`
to
> `⚠️ Failed to compute a project ID from the given inputs`
> fix !project_id error message typo

- action.yml
- src/main.ts
- src/post.ts
> Use our custom boolean parsing
