- dist/index.js
- package-lock.json
- package.json
- src/client.ts
- src/main.ts
Use latest actions/core beta release for generating the GH OIDC token.
> feat: use actions/core for generating GH OIDC token

- .github/workflows/test.yaml
- README.md
- action.yml
- dist/index.js
- package-lock.json
- src/client.ts
- src/main.ts
This credentials file can be passed to gcloud or other Google Cloud SDKs to automatically do the exchange.
Closes #6
> Add the ability to generate and export a credentials file

- .github/workflows/test.yaml
- README.md
- action.yml
- dist/index.js
- package.json
- src/client.ts
Will still need to fix the CI job, but @bharathkkb is working on provisioning that infra.
> Update references to google now

- README.md
- action.yml
- dist/index.js
- src/main.ts
Fixes GH-22
GitHub says this is still rolling out, but here's the high-level change.
> Default audience to the WIF provider ID

- .github/workflows/test.yaml
Tested this on my fork @bharathkkb and it worked.
> Fallback to ref

- dist/index.js
- src/main.ts
Also import less of `core`, which should improve startup times and reduce the file size (a little bit).
> Output more information in error about missing secrets

- dist/index.js
- src/main.ts
- exports an env var for authenticating in https://github.com/google-github-actions/setup-cloud-sdk
> fix: export Google GHA creds env var

- README.md
> Note that Domain-Wide Delegation is not supported

- README.md
Add a link to the TF module incase users are interested in managing WIF infra via TF
> chore: add a link to TF module

- README.md
- action.yml
- dist/post/index.js
- src/post.ts
> bug: only cleanup credentials if credentials were created

- src/main.ts
> chore: warn if the action is pinned to HEAD

- README.md
> chore: switch to new setup-gcloud workflow

- README.md
> chore: fix readme example to not consume token

- README.md
Replace single quotes with double quotes in README.
> Replace single quotes with double quotes in README

- README.md
- docs/TROUBLESHOOTING.md
I feel like we have a common class of issues. I started some troubleshooting steps for folks in the README.
Fixes https://github.com/google-github-actions/auth/issues/124
> doc: add troubleshooting section

- README.md
Fixes https://github.com/google-github-actions/auth/issues/126
> docs: add gar and gcr example

- docs/TROUBLESHOOTING.md
> doc: add more troubleshooting

- README.md
https://github.com/google-github-actions/auth/blob/main/action.yml#L136-L139
> doc: Fix token_format in readme.

- .github/dependabot.yml
> chore: add dependabot settings

- .github/workflows/test.yml
- .gitignore
- README.md
>  chore: update references to setup-gcloud@master -> setup-gcloud@main

- .github/workflows/draft-release.yml
- .github/workflows/release.yml
Update to new release process!
> chore: update release process

- README.md
Refs https://github.com/google-github-actions/auth/issues/368
> Add service_account to WIF through SA example

- README.md
Closes https://github.com/google-github-actions/auth/pull/375
(Opening as me to trigger CI)
> Note .dockerignore in the exclusion for credentials

- README.md
> Recommend `gcloud storage` over `gsutil`

- src/main.ts
> Add retries for getIDToken
